from CeurWsParser.parsers.workshop_parser import WorkshopSummaryParser, WorkshopPageParser, WorkshopRelationsParser
from CeurWsParser.parsers.proceedings_parser import ProceedingsSummaryParser, EditorAffiliationParser
from CeurWsParser.parsers.publication_parser import PublicationParser
from CeurWsParser.parsers.pdf_parser import PDFParser
from CeurWsParser.parsers.base import Parser