from CeurWsParser.parsers.workshop_parser import WorkshopSummaryParser, WorkshopPageParser, WorkshopAcronymParser, \
    WorkshopRelationsParser, JointWorkshopsEditorsParser, EditorAffiliationParser
from CeurWsParser.parsers.proceedings_parser import ProceedingsSummaryParser, ProceedingsRelationsParser
from CeurWsParser.parsers.publication_parser import PublicationParser, PublicationNumOfPagesParser
from CeurWsParser.parsers.pdf_parser import PDFParser
from CeurWsParser.parsers.base import Parser, ListParser