SELECT DISTINCT (STRDT(?acrn, xsd:string) AS ?acrn_str) (YEAR(?conf_date) AS ?conf_date_int) ?proc {
  VALUES (?acrn ?year) {
    ("ISWC" "2012")
  }
  ?conf a swc:OrganizedEvent ;
        rdfs:label ?conf_name ;
        timeline:atDate ?conf_date .
  ?workshop swc:isSubEventOf ?conf .
  ?proc bibo:presentedAt ?workshop .
  FILTER( ?conf_name = ?acrn && STR(YEAR(?conf_date)) = ?year )
  FILTER EXISTS { ?workshop skos:related [] . }
  FILTER NOT EXISTS { [] skos:related ?workshop . }
}