SELECT (STRDT(?prefix, xsd:string) AS ?prefix_a) (SUM(?edition) AS ?edition_count) {
  {
    SELECT ?prefix (MAX(?edition) AS ?max_edition) {
      VALUES ?prefix {
        "Linked Data on the Web"
        "Workshop on Modular Ontologies"
      }
      ?workshop a bibo:Workshop ;
        rdfs:label ?workshop_name .
      OPTIONAL { ?workshop swrc:edition ?e . }
      BIND (IF(bound(?e), ?e, 1) AS ?edition)
      FILTER(STRSTARTS(?workshop_name, ?prefix))
    }
    GROUP BY ?prefix
  }
  {
    SELECT ?prefix ?edition {
      VALUES ?prefix {
        "Linked Data on the Web"
        "Workshop on Modular Ontologies"
      }
      ?workshop a bibo:Workshop ;
        rdfs:label ?workshop_name .
      OPTIONAL { ?workshop swrc:edition ?e . }
      BIND (IF(bound(?e), ?e, 1) AS ?edition)
      FILTER(STRSTARTS(?workshop_name, ?prefix))
    }
  }
  FILTER(?max_edition = ?edition)
}
GROUP BY ?prefix